module.exports = Object.freeze({
    SYSTEM_INFO_INTERVAL: 500,
    UI_UPDATE_TIMEOUT: 500,
    KEYBOARD_ATTACH_DELAY: 5000,
    PORT: 3456,
    OS: {
        WINDOWS: "Windows",
        MAC: "MacOS",
        LINUX: "Linux",
    },
    SYSINFO_PATH: "logs/systemInfo.log",
    WINDOW_MSG_OK: "",
    WINDOW_MESSAGE_ERROR: "",
    KEEB_LAYERS: [
        "QWERTY",
        "COLEMAK_DH",
        "MACOS",
        "MIDI",
        "FUNC",
        "FUNC_MAC",
        "MAPS",
    ],
    ENCODER_STATES: ["_", "MACROS", "SCROLL"],
    OS_STATES: ["WIN", "MAC"],
    CHAR_TO_CODE_MAPPING: {
        " ": 1,
        A: 4,
        B: 5,
        C: 6,
        D: 7,
        E: 8,
        F: 9,
        G: 10,
        H: 11,
        I: 12,
        J: 13,
        K: 14,
        L: 15,
        M: 16,
        N: 17,
        O: 18,
        P: 19,
        Q: 20,
        R: 21,
        S: 22,
        T: 23,
        U: 24,
        V: 25,
        W: 26,
        X: 27,
        Y: 28,
        Z: 29,
        1: 30,
        2: 31,
        3: 32,
        4: 33,
        5: 34,
        6: 35,
        7: 36,
        8: 37,
        9: 38,
        0: 39,
        _: 44,
        "-": 45,
        "=": 46,
        "[": 47,
        "]": 48,
        "\\": 49,
        "#": 50,
        ";": 51,
        "'": 52,
        "`": 53,
        ",": 54,
        ".": 55,
        "/": 56,
        ":": 57,
    },
});